### ISSUE TITLE
misssing figure links, wrong accession/specimen codes, not in google search AD37FFDD6D52FF91273DFFC9FFB8FFF2

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#114]
this species Centruroides catemacoensis does not show up in google search, although we have it in TB.

https://tb.plazi.org/GgServer/html/510E87A56D5DFF812795FB10FB03F938

might it be possible to do QC and check, why the figures are not linked.

Also please check the specimen codes which are misinterpreted and linked as accession codes

This is also part of the CAS press release.

Good to see that the Bulletins 2021 are processed

**Comment by diegojalvares** [comment]
Fixed

**Comment by myrmoteras** [comment]
@diegojalvares this has still an issue with the the accession/ specimen code.

![image](https://user-images.githubusercontent.com/4609956/148535598-e289a73c-e866-4d2f-98c3-092a94286127.png)

CNAN the cnan view materials resolves erroneously to C. elegans. https://www.ncbi.nlm.nih.gov/nucleotide/T01414 and not to the specimen.

@flsimoes @mguidoti do we have somewhere a place where store false positive specimen/accession codes? 
We need this for BiCIKL bidirectional linking to improve guidos' algorithms

**Comment by flsimoes** [comment]
> @diegojalvares this has still an issue with the the accession/ specimen code.
> 
> ![image](https://user-images.githubusercontent.com/4609956/148535598-e289a73c-e866-4d2f-98c3-092a94286127.png)
> 
> CNAN the cnan view materials resolves erroneously to C. elegans. https://www.ncbi.nlm.nih.gov/nucleotide/T01414 and not to the specimen.
> 
> @flsimoes @mguidoti do we have somewhere a place where store false positive specimen/accession codes? We need this for BiCIKL bidirectional linking to improve guidos' algorithms

No, we don't. I think that Guido should suggest a place where he would like to see these sort of examples be compiled and that he can constantly check (or check whenever he feels like it). Otherwise we risk having storages that are just left unused for a long time.

**Comment by diegojalvares** [comment]
Hi
I removed the annotations related to accession numbers
I hope that solve the problems

**Comment by flsimoes** [comment]
Is this sorted? If so, please close the issue

**Comment by myrmoteras** [comment]
@flsimoes   it would be helpful to have a place where we store such fals positive. this is at the core of BiCIKL bidirectional linking, discussions with ENA, etc and something we need to progress in the coming year.

**Comment by mguidoti** [comment]
A spreadsheet with a couple of columns (Article UUID, page, paragraph, actual string of the accession number, resolving URL with applicable) shared with Guido should do the trick. 

However, it concerns me a lot this continue 'list collect examples' approach, because we generally will lose or discontinue a list of examples due to our lack of agreement in how and where we should keep them - and even worse, we have an inclination in repeating the effort because we've lost the original list. Perhaps we should address this?

**Comment by flsimoes** [comment]
My main concern has always been the trackability of the collection of examples.
Whether it is within a repository or spreadsheet or whatever else, we usually only see similar examples after a long time of finding the first case, meaning we mostl likely won't even remember that we already started a discussion on that particular topic.

Addressing this matter requires two main points to me: **where** to store (as Marcus just said) and **how** to store. Ideally we should have a fast and easy way of knowing whether a particular discussion/collection of examples has already started; the first thing that comes to my mind are keywor, but even that is not 100%.

**Comment by myrmoteras** [comment]
We need to collect this samples in order to improve specimen code, collection code and accession code parsing.

If it is too complicated to create a spreadsheet and remeber it, then we do not do it and somebody will spend a day or so to check codes when we in the near future will revise those parsers and linkers.

.

**Comment by mguidoti** [comment]
Hi Donat, 

We are just trying to find a way where we don't waste human efforts not lose good examples. That's all. I could think of three:

1) Let's use [/ggi](https://github.com/plazi/ggi/) repo using Discussions in there, in a specific category, created for this purpose. Then, we just create a regular issue with `[EXAMPLE]` in the title, and add a tag specific to that type of collection of examples (say, `e.g. of accessionNumber`). Finally, someone in the production facility curate this and migrate the issue to the right discussion type, making sure the correct tag was used. In that way, we can record the examples with prints and have discussions about it, and we can filter from the rest by using the Discussion>>Examples, and finally, from one list of examples to the other by the tags. 
PS: We could add PDFs here, or links from Google Drive to these PDFs (even better).

2) We can still use [/ggi](https://github.com/plazi/ggi/) repo but add all examples of a given collection into the same issue. We would still be using the Discussions to separate them from the rest, but special tags wouldn't be necessary. I think discussions and debates about specific example within a given collection of examples would become messy, as the responses would be mixed with new examples and so on.

3) We could create a Shared Drive with spreadsheets and collect these examples in spreadsheets, like I mentioned before here in this issue/thread. The biggest issue here would be handling print screens (I literally just realized that). As they are not suitable in spreadsheets, we would have to save it externally and add a link to the file in the spreadsheet. Too many steps, I would say.

Finally,  I would add a webpage on intra.plazi.org simply called `Examples`, where we could add the links to the already filtered Discussion type, per collection of examples - that's to facilitate navigation, filtering, finding. Just to mention that we have examples for all sort of things, including to build screencasts, which have been collected by the production facility for months now. By having this discussion now and making this call, you're helping us organize a big issue on our side (organization of collection of examples).

I estimate organizing these whole thing in 1h, 2h tops. 

What do you think? Honestly, I think we (and you) would work better with the first method, especially combined with the intra page with pre-set links and filters.

Cheers,
