### ISSUE TITLE
Incorrect interpretation of Institution code "BPS"

### ISSUE THREAD

**Issue by tcatapano** [plazi/community#228]
The code "BPS" used in material citations for this treatment refer to the "Bill P. Stark [BPS] collection", not the California Department of Food and Agriculture. See the Materials and Methods section of the parent article at: https://doi.org/10.5281/zenodo.4760725

> Most Allocapnia specimens were provided by the Stark Collection,  Mississippi College, Clinton, Mississippi  (BPS)

and per email of Mac Alford (Mac.Alford@usm.edu) to @tcatapano  2023-04-03:

> I was recently checking a GBIF record of stoneflies (Insecta: Plecoptera) that I collected, and I noticed that a record was misattributed to the country of Turkey, instead of the USA. (The label indicated Turkey Creek in the US state of Ohio. These are in the Bill P. Stark [BPS] collection.)

**Context**
[GBIF occurrence](https://www.gbif.org/occurrence/3111537375)
[Plazi reference](https://treatment.plazi.org/id/C86087E1932BF45942C4FCA2FD3DFCFC

**Comment by flsimoes** [comment]
This has been fixed by @diegojalvares

**Comment by tcatapano** [comment]
On GBIF, Institution code "BPS" is still showing up as "California Department of Food and Agriculture". Perhaps this interpretation is not on the Plazi end, but GBIF's?

**Comment by flsimoes** [comment]
> On GBIF, Institution code "BPS" is still showing up as "California Department of Food and Agriculture". Perhaps this interpretation is not on the Plazi end, but GBIF's?

let me check

**Comment by flsimoes** [comment]
So, the BPS actually refers to "Stark Collection, Mississippi College, Clinton, Mississippi"
![image](https://github.com/user-attachments/assets/b6fd7d60-98c8-49aa-98fe-d5e113070730)

**Comment by flsimoes** [comment]
Currently it shows as "Bioparco di Sicillia"
![image](https://github.com/user-attachments/assets/fcf24e2a-c4f9-4636-864c-f09f63ae09eb)

As we only send the collectionCode through, it seems to be a GBIF issue.
