### ISSUE TITLE
Wasp with classification problems - D94BFFF8813AFFDE7016D56B781FFFE2

### ISSUE THREAD

**Issue by camiplata** [plazi/community#377]
Some species are under the wrong order all of them should be Hymenoptera:

https://www.checklistbank.org/dataset/8654/classification?taxonKey=x8
https://tb.plazi.org/GgServer/summary/D94BFFF8813AFFDE7016D56B781FFFE2

<img width="881" alt="Image" src="https://github.com/user-attachments/assets/8e659f58-0844-4642-ac87-162667e127c3" />

The classification hierarchy needs to be fixed it should be Hymenoptera > Vespidae > Eumeninae

<img width="554" alt="Image" src="https://github.com/user-attachments/assets/109ede82-3dba-4606-95d5-5443e311104d" />

**Comment by JonasBlanco** [comment]
Done! Waiting for ChecklistBank updating now...

**Comment by camiplata** [comment]
Almost there, the classification is still showing "Emumenidae" and "Vespidae" as Families, according to the paper Eumeni`nae` is a subfamily of Vespidae

<img width="418" alt="Image" src="https://github.com/user-attachments/assets/917d73d9-9a43-4620-ade8-855abecbc5b4" />

**Comment by JonasBlanco** [comment]
I already changed that, maybe is a matter of waiting a little bit for the updated info.
I'll monitor it.

**Comment by JonasBlanco** [comment]
Now it's fixed.
