### ISSUE TITLE
Bad authorships

### ISSUE THREAD

**Issue by mdoering** [plazi/community#432]
2 treatments in this article have bad authorships with a colon `:` prefixing it
https://www.checklistbank.org/dataset/21551/taxon/03E387995E15FFE0FF36F93FFD2935BE.taxon

**Comment by mdoering** [comment]
https://treatment.plazi.org/id/03E387995E15FFE0FF36F93FFD2935BE

**Comment by Carol-Sokolowicz** [comment]
This was fixed

**Comment by mdoering** [comment]
Does it take some time until TreatmentBankd and the DwCA updates?
They both still show the colons:
```
03E387995E16FFE1FF36FE59F8AF37C3.taxon					Animalia	Arthropoda	Insecta	Plecoptera	Perlodidae	Isoperla	species	Isoperla asiatica : Rauser 1968	: Rauser 1968	Isoperla asiatica	Isoperla asiatica Raušer, 1968			: Rauser	1968			https://treatment.plazi.org/id/03E387995E16FFE1FF36FE59F8AF37C3
03E387995E15FFE0FF36F93FFD2935BE.taxon					Animalia	Arthropoda	Insecta	Plecoptera	Perlodidae	Isoperla	species	Isoperla eximia : Zapekina-Dulkeit 1975	: Zapekina-Dulkeit 1975	Isoperla eximia	Isoperla eximia Zapekina-Dulkeit, 1975			: Zapekina-Dulkeit	1975			https://treatment.plazi.org/id/03E387995E15FFE0FF36F93FFD2935BE
```
<img width="672" alt="Image" src="https://github.com/user-attachments/assets/ebebf706-0d86-4e03-909a-004e6a8a84d7" />

**Comment by Carol-Sokolowicz** [comment]
it usually takes a few minutes, but it should be updated now
